repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: trailing-whitespace
      exclude: '\.expected$'
    - id: end-of-file-fixer
      exclude: '\.expected$'
    - id: check-yaml
    - id: check-toml
    - id: check-ast
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: detect-private-key
    - id: debug-statements

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

-   repo: local
    hooks:
      - id: check-main-in-examples
        name: ensure all example scripts have main()
        entry: python scripts/lint_examples_main.py
        language: system
        files: ^examples/.*\.py$

-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.405
    hooks:
      - id: pyright
        language: system
